### ISSUE TITLE
yarn link + yalc add deletes all project files :(

### ISSUE THREAD

**Issue by treffynnon** [whitecolor/yalc#7] opened 2017-09-15 05:30 UTC
Inside my project I've got a package.json file that has been configured for `npm publish` to only publish selected files:

```json
...
  "files": [
    "build",
    "yarn.lock"
  ],
...
```

Unfortunately, I lost work that I had in my git stash when I then executed `yalc publish` and everything but those specified paths was deleted including `.git`.

**Comment by whitecolor** [comment] 2017-09-15 10:08
Can you reproduce it on simple directory?
[yalc should be not touching any files in your publish directory, it just copies them.](https://github.com/whitecolor/yalc/blob/master/src/publish.ts#L58)

**Comment by treffynnon** [comment] 2017-09-15 11:31
I've thought about it further (now I am calmer too!) and I've realised it was a combination of my not fully understanding how yalc shared the project and the fact that there is a `.yarnclean` file in my parent project. So what must've happened is:

1. I went into my dependency (child) project and ran `yalc publish` - so far so good
2. Moved into my dependent (parent) project and ran `yalc add my-package` - still ok
3. Now I run `yarn` to grab all the required 3rd party/vendor packages for the child project - danger approaches
4. As yarn install is nearing it's end; yarn notices I've got a `.yarnclean` file and proceeds to gut the now symlinked child directory
5. Whoops!

So, this is a combination of moving too quickly and forgetting about `.yarnclean` I think. I've not had a chance to test, but I am pretty sure this is the most likely reason.

**Comment by whitecolor** [comment] 2017-09-15 12:19
I'm still not sure when you get symlinks and what are they, yalc actually is specially designed to get rid of symlinks to source package directory. I'm not so familiar with yarnclean functionality, if it cleans up packages inside node_modules it still should not touch anything in source directories.

**Comment by treffynnon** [comment] 2017-09-15 15:39
I've reproduced. It's not specifically the `.yarnclean` file, but it is yarn.

In the child if you've got `files` defined in package.json and you use yalc to add it to the parent project all is fine. Now when you run `yarn` install to pull in the required dependencies the child no longer has any files that aren't defined in the `files` of package.json.

**Comment by treffynnon** [comment] 2017-09-15 15:43
See https://github.com/treffynnon/yalc-repro

Steps to reproduce with that repo cloned.

```bash
cd child
ls -lkha #note file list
yalc publish
cd ../parent
yalc add child
yarn
ls -lkha ../child #compare with previous file listing
```

**Comment by whitecolor** [comment] 2017-09-15 20:20
I did that so I see nothing wrong with source `child` dir. Being inside `parent` you can hardly reach source `child` directory with yarn, there is no even single symlink in the setup. )

**Comment by treffynnon** [comment] 2017-09-17 23:42
Thats weird. I wonder what would be different about my environment I using yarn @ v1.0.2.

**Comment by whitecolor** [comment] 2017-09-18 03:02
Just tried 1.0.2

I just really can not imagine how doing anything in parent can affect source child directory. They are completely detached.

while publish source `child` goes to ---> yalc_global_storage/packages/child
while add in parent source from yalc_global_storage/packages/child goes to parent/.yalc/child and parent/node_modules/child

Maybe I'm not getting something? Any suggestion?

**Comment by treffynnon** [comment] 2017-09-18 04:10
I think I might have been able to isolate it now - it is most likely a combination of yarn link and yalc. The following plays out that setup. I had my project linked and then realised it wasn't enough so installed yalc, did not think to yarn unlink first and just published & added with yalc.

```bash
cd child

echo "child 1st ls" > ls1.txt
ls -lh ../child >> ls1.txt
echo "----------------------" >> ls1.txt

yarn link
cd ../parent
yarn link child
cd ../child
yalc publish
cd ../parent

echo "child 2nd ls" > ls2.txt
ls -lh ../child >> ls2.txt
echo "----------------------" >> ls2.txt

yalc add child

echo "child 3rd ls" > ls3.txt
ls -lh ../child >> ls3.txt
echo "----------------------" >> ls3.txt

cat ls1.txt ls2.txt ls3.txt
```

Gives me this:

```
child 1st ls
total 16
drwxr-xr-x  4 simon  staff   136B 18 Sep 14:02 build
-rw-r--r--  1 simon  staff     0B 18 Sep 14:04 index.js
-rw-r--r--  1 simon  staff   116B 18 Sep 14:04 package.json
-rw-r--r--  1 simon  staff     0B 18 Sep 14:04 test.png
-rw-r--r--  1 simon  staff    32B 18 Sep 14:02 yalc.sig
----------------------
child 2nd ls
total 16
drwxr-xr-x  4 simon  staff   136B 18 Sep 14:02 build
-rw-r--r--  1 simon  staff     0B 18 Sep 14:04 index.js
-rw-r--r--  1 simon  staff   116B 18 Sep 14:04 package.json
-rw-r--r--  1 simon  staff     0B 18 Sep 14:04 test.png
-rw-r--r--  1 simon  staff    32B 18 Sep 14:02 yalc.sig
----------------------
child 3rd ls
total 16
drwxr-xr-x  4 simon  staff   136B 18 Sep 14:04 build
-rw-r--r--  1 simon  staff   124B 18 Sep 14:04 package.json
-rw-r--r--  1 simon  staff    32B 18 Sep 14:04 yalc.sig
```

**Comment by whitecolor** [comment] 2017-09-18 10:42
> I think I might have been able to isolate it now - it is most likely a combination of yarn link and yalc. The following plays out that setup.

Yeah right, of course you should not use `yarn link` and `yalc add/link` for the same package. With `yarn link` you create link in parent/node_modules/child, and yalc copies there package files and it also cleans it up =)

Actually `yalc add/link`  is here to replace `yarn link` with more consistent workflow so to get rid of symliking to source folders.

**Comment by treffynnon** [comment] 2017-09-18 22:47
Moving quickly I didn't notice that this was the case or that the module was still symlinked. I think a warning in the readme or better yet detecting a symlink before `yalc add` and halting with an error could help to prevent others from running into this in the future.

It would seem likely common to me that new users of yalc would be working with `(yarn || npm) link` and then switch to yalc when they realise it's not working for them.

**Comment by whitecolor** [comment] 2017-09-19 08:32
> detecting a symlink before

Yes I think this would be correct to do this. I'll add this check.

**Comment by dsnoeck** [comment] 2017-09-19 12:10
I had similar issue recently. `.git` folder and even my `gulpfile.js` where suddenly missing !
I didn't use yarn but I might had use `npm link`. I didn't pay attention to those details before. And now I cannot reproduce the issue. So I just keep a comment here in case I can provide more info.

**Comment by whitecolor** [comment] 2017-10-24 17:04
Should be fixed now.

**Closed by whitecolor** 2017-10-24 17:04 UTC
